### ISSUE TITLE
Data Fragmentation at High Baud Rates Due to Short Timeout Intervals.

### ISSUE THREAD

**Issue by citax** [ConstantRobotics-Ltd/SerialPort#7]
When data is printed at very high speeds from the serial port, the library is unable to receive the incoming message in one go. This is valid for cases where the timeout period is kept short, and the serial port is constantly scanned. For example, a message packet like [0xFF, 0x0A, 0x0A] is detected in two parts as [0xFF] and [0x0A, 0x0A]. Can an example be written for this situation? Frankly, I solved this problem myself by merging the data in my temp buffer after encountering two consecutive timeouts. However, it would be better if this issue is resolved within the library. Idle detection could be used, for instance.

**Comment by ConstantRobotics** [comment]
Thank you for comment! Generally when user call read(...) function the library checks if there is any data in input buffer. If there is data the library will return it. It can be part of message because serial port is not synchronous interface. If no input data in buffer the library will wait until data will come or until timeout expired. During wait time the library check if whole message receiver (start byte -> end byte). So, it is impossible to provide exactly necessary for you behavior because: serial port not synchronous interface and we depend on user's call of read(...) function. For example, if processing of incoming message it too long for next call of read(...) function you may get few combined messages. So, user should have message format detection mechanism. Use ring buffer to detect messages especially if you have constant message length.

**Comment by citax** [comment]
Hello, first of all, thank you for your response. I am aware at some point that this is nearly impossible. In the code I am currently using, I am working with a ring buffer and then parsing the data from the buffer. However, the biggest issue is that the size of the incoming data is constantly variable. The incoming UART data doesn't have any stop bits or information about the size. In short, I am writing code for a rather strange system. I solved this in embedded systems using IDLE detection. I wanted to ask if there is a similar solution like IDLE in Windows drivers or if your library supports such a feature. Thanks again!
